### ISSUE TITLE
Could you please share the code of your "motivating example" in section 3.1?

### ISSUE THREAD

**Issue by Bhongcheng** [Yutong-Dai/FedNH#2]

**Comment by Yutong-Dai** [comment]
Your request is received. Due to the fact that I've lost access to the server, I need to rewrite a script for this part. I will upload the result by the end of this weekend and let you know then. Thanks!

**Comment by Bhongcheng** [comment]
Thanks for your reply.

**Comment by Yutong-Dai** [comment]
Hi @Bhongcheng,

Please find the [notebook](https://github.com/Yutong-Dai/FedNH/blob/main/examples/motivation_examples.ipynb) to reproduce the plots provided in Section 3.1.

Cheers,
YD

**Comment by Bhongcheng** [comment]
Thanks
