### ISSUE TITLE
About the utils.py def sampler()

### ISSUE THREAD

**Issue by Bhongcheng** [Yutong-Dai/FedNH#3]
![截屏2023-03-10 19 01 10](https://user-images.githubusercontent.com/90205287/224300903-0dc28d34-755c-4189-b5b8-2e84ba12b748.png)
It makes me confused... beta is a float value, what is the meaning of "beta.split('b')"?
Thanks.

**Comment by Yutong-Dai** [comment]
This is my bad as I should have writtend down more comments.  
This code snippet is written for testing *the Dirichlet partition* with balanced and imbalanced sample sizes. 
In the configuration file where you specify the parameter for simulating Dir(beta), you can use '0.3b' and '0.3' to set the value for the `beta` parameter. 
If you use `0.3b`, then the partition function tries to allocate each client with nearly the same number of training samples. And that is precisely what 'b' stands for, balancedness.
