### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by Bhongcheng** [Yutong-Dai/FedNH#4]
hi, I still have some questions to bother you.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/90205287/224477899-71591574-d0f0-4528-84ae-9762640a159f.png">
1. If the data partition is  unbalanced, the weight of each update_aggregation is still the same, which is maybe not reasonable?
2. Why acting aggregation in such a complicated way... I think just simply aggregating them by the weights (sample_num / total_num) is enough...
3. Why using server_lr_decay, which is not common in other paper?
4. Should this function be in the server.py, since other strategies in the code don't implement "def aggregate()".

Really sorry to bother you again.

**Comment by Yutong-Dai** [comment]
Hi @Bhongcheng ,
No worries at all! Thanks for your interest in the code and you may ask as many questions as you would like to.  Please see my answers below.

1. This is more about your understanding of "fairness aggregation" among clients. To me, we should treat clients equally important regardless of the amount of data they hold locally. With that being said, I set equal aggregation weights for active clients for the weight aggregation. Similar choices are also made in [FedProx, Theorem 2](https://arxiv.org/pdf/1812.06127.pdf). Another good thing about this equal aggregation choice is that clients do not expose their data volume, which you may argue is private information to the server.  
2. Please see the answer to Q1.  Feel free to have more follow-up questions on this point.
3. `server_lr_decay` is implemented to provide more flexibility. If you are familiar with stochastic optimization, you may recognize that the decay learning rate is a way to achieve variance reduction, which could potentially improve convergence. But in all experiments conducted in the paper, for the fair comparison purpose, the `server_lr = 1.0` as you can tell from the config yaml files, for example, https://github.com/Yutong-Dai/FedNH/blob/60c3161412d576cddc8187af318cdc8a91a8709f/experiments/Cifar100_Conv2Cifar.yaml#L28
4. I am not sure which file you are looking at. But I think you take the screenshot from [here](https://github.com/Yutong-Dai/FedNH/blob/60c3161412d576cddc8187af318cdc8a91a8709f/src/flbase/strategies/FedAvg.py#L131). The reason I implemented here is that  I want to keep the `Server` class https://github.com/Yutong-Dai/FedNH/blob/60c3161412d576cddc8187af318cdc8a91a8709f/src/flbase/server.py#L10 generic enough for future extension. Some future methods may have completely different aggregation rules.

Best,
YD

**Comment by Bhongcheng** [comment]
Thanks for your warm and detailed reply!
